// Exact identities retained after BLOQ left the catalog, for old links and browser saves.
export const RETIRED_BLOQ_COLOR_SLUGS = [
  "assembly-201-saffron",
  "assembly-202-vermillion",
  "assembly-501-iceblue",
  "assembly-502-aquamarine",
  "assembly-601-chartreuse",
  "assembly-901-cement",
  "balance-111-truffle",
  "balance-123-greige",
  "balance-124-walnut",
  "balance-125-flax",
  "balance-130-sahara",
  "balance-135-nutmeg",
  "balance-218-paprika",
  "balance-410-fuchsia",
  "balance-522-atlantic",
  "balance-530-sea",
  "balance-617-moss",
  "balance-812-coffee",
  "balance-907-iron",
  "balance-911-mouse",
  "balance-921-elephant",
  "balance-937-ash",
  "balance-942-shadow",
  "balance-946-graphite",
  "canvas-140-cotton",
  "canvas-145-ivory",
  "canvas-150-pearl",
  "canvas-220-melon",
  "canvas-225-amber",
  "canvas-230-lime",
  "canvas-310-sienna",
  "canvas-415-lilac",
  "canvas-535-sky",
  "canvas-540-bluestone",
  "canvas-625-sage",
  "canvas-815-olive",
  "canvas-820-timber",
  "canvas-935-slate",
  "canvas-955-silver",
  "canvas-960-concrete",
  "canvas-965-smoke",
  "canvas-970-storm",
  "connexion-122-dusty-trail",
  "connexion-206-smoky-track",
  "connexion-217-burnt-alley",
  "connexion-406-soft-road",
  "connexion-506-toned-route",
  "connexion-526-clear-path",
  "connexion-611-cool-passage",
  "connexion-926-silent-lane",
  "flow-111-truffle",
  "flow-123-greige",
  "flow-124-walnut",
  "flow-125-flax",
  "flow-130-sahara",
  "flow-135-nutmeg",
  "flow-218-paprika",
  "flow-410-fuchsia",
  "flow-522-atlantic",
  "flow-530-sea",
  "flow-617-moss",
  "flow-812-coffee",
  "flow-907-iron",
  "flow-911-mouse",
  "flow-921-elephant",
  "flow-937-ash",
  "flow-942-shadow",
  "flow-946-graphite",
  "grain-111-truffle",
  "grain-123-greige",
  "grain-124-walnut",
  "grain-125-flax",
  "grain-130-sahara",
  "grain-135-nutmeg",
  "grain-218-paprika",
  "grain-410-fuchsia",
  "grain-522-atlantic",
  "grain-530-sea",
  "grain-617-moss",
  "grain-812-coffee",
  "grain-907-iron",
  "grain-911-mouse",
  "grain-921-elephant",
  "grain-937-ash",
  "grain-942-shadow",
  "grain-946-graphite",
  "large-155-rice",
  "large-207-dijon",
  "large-211-pumpkin",
  "large-306-scarlet",
  "large-516-ultra-marine",
  "large-621-spring",
  "medium-928-thunder",
  "negative-222-peach",
  "negative-227-dune",
  "negative-232-pear",
  "negative-627-rosema",
  "negative-817-pine",
  "negative-822-cedar",
  "negative-972-fog",
  "negative-981-fossil",
  "positive-221-salmon",
  "positive-226-corn",
  "positive-231-tea",
  "positive-626-fennel",
  "positive-816-nut",
  "positive-821-celery",
  "positive-971-grit",
  "positive-980-silt",
  "renegade-111-truffle",
  "renegade-123-greige",
  "renegade-124-walnut",
  "renegade-125-flax",
  "renegade-130-sahara",
  "renegade-135-nutmeg",
  "renegade-218-paprika",
  "renegade-410-fuchsia",
  "renegade-522-atlantic",
  "renegade-530-sea",
  "renegade-617-moss",
  "renegade-812-coffee",
  "renegade-907-iron",
  "renegade-911-mouse",
  "renegade-921-elephant",
  "renegade-937-ash",
  "renegade-942-shadow",
  "renegade-946-graphite",
  "rhythm-121-melody",
  "rhythm-216-motion",
  "rhythm-521-synchrony",
  "rhythm-616-sound",
  "rhythm-811-silence",
  "rhythm-906-mute",
  "rhythm-936-beat",
  "rhythm-941-frequency",
  "sculpture-111-truffle",
  "sculpture-123-greige",
  "sculpture-124-walnut",
  "sculpture-125-flax",
  "sculpture-130-sahara",
  "sculpture-135-nutmeg",
  "sculpture-218-paprika",
  "sculpture-410-fuchsia",
  "sculpture-522-atlantic",
  "sculpture-530-sea",
  "sculpture-617-moss",
  "sculpture-812-coffee",
  "sculpture-907-iron",
  "sculpture-911-mouse",
  "sculpture-921-elephant",
  "sculpture-937-ash",
  "sculpture-942-shadow",
  "sculpture-946-graphite",
  "sensity-503-deep-sea",
  "sensity-602-patina",
  "sensity-902-pietra-grey",
  "sensity-903-grey-marble",
  "small-156-salt",
  "small-208-honey",
  "small-212-tangerine",
  "small-307-ruby",
  "small-517-persian-blue",
  "small-622-fern",
  "solace-165-off-white",
  "solace-170-light-taupe",
  "solace-240-indian-summer",
  "solace-550-smoke-blue",
  "solace-630-fern",
  "solace-640-eucalyptus",
  "solace-830-driftwood",
  "solace-975-pepperwhite",
  "solace-985-northsea",
  "solace-990-granite",
  "solace-995-carbon",
  "tradition-105-hemp",
  "tradition-110-linen",
  "tradition-115-birch",
  "tradition-120-peat",
  "tradition-205-mustard",
  "tradition-210-orange",
  "tradition-215-terra",
  "tradition-305-red",
  "tradition-405-pink",
  "tradition-505-denim",
  "tradition-510-midnight",
  "tradition-515-sapphire",
  "tradition-520-ocean",
  "tradition-525-teal",
  "tradition-605-ice",
  "tradition-610-jade",
  "tradition-615-forest",
  "tradition-620-grass",
  "tradition-805-fox",
  "tradition-810-bark",
  "tradition-905-rock",
  "tradition-910-stone",
  "tradition-915-cloud",
  "tradition-920-dust",
  "tradition-925-flint",
  "tradition-930-gray",
  "tradition-935-slate",
  "tradition-940-anthracite",
  "tradition-945-coal",
  "tradition-950-black",
  "unity-203-golden-ecru",
  "unity-302-crimson",
  "unity-504-oxford-blue",
  "unity-603-lichen",
  "unity-904-old-zinc",
  "unity-905-blue-grey",
] as const;

export const RETIRED_BLOQ_COLLECTION_SLUGS = [
  "bloq-assembly",
  "bloq-balance",
  "bloq-canvas",
  "bloq-connexion",
  "bloq-flow",
  "bloq-grain",
  "bloq-large",
  "bloq-medium",
  "bloq-negative",
  "bloq-positive",
  "bloq-renegade",
  "bloq-rhythm",
  "bloq-sculpture",
  "bloq-sensity",
  "bloq-small",
  "bloq-solace",
  "bloq-tradition",
  "bloq-unity",
] as const;

const retiredIds = new Set<string>([
  ...RETIRED_BLOQ_COLOR_SLUGS,
  ...RETIRED_BLOQ_COLLECTION_SLUGS,
  ...RETIRED_BLOQ_COLLECTION_SLUGS.flatMap(slug => [`bloq-coll-${slug}`, `bloq-${slug}`]),
]);

export function isRetiredBloqReference(value: unknown): boolean {
  if (typeof value !== 'string' || !value.trim()) return false;
  const reference = value.trim();
  if (retiredIds.has(reference)) return true;
  try {
    const url = new URL(reference, 'https://www.podovi.online');
    const slug = decodeURIComponent(url.pathname).split('/').filter(Boolean).pop() || '';
    return retiredIds.has(slug)
      || retiredIds.has(url.searchParams.get('product') || '')
      || retiredIds.has(url.searchParams.get('color') || '');
  } catch {
    return false;
  }
}

export function isRetiredBloqProduct(product: {
  id?: unknown;
  slug?: unknown;
  brandId?: unknown;
  collectionSlug?: unknown;
  url?: unknown;
} | null | undefined): boolean {
  return product?.brandId === '8'
    || [product?.id, product?.slug, product?.collectionSlug, product?.url].some(isRetiredBloqReference);
}
